name: Create Pre-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the pre-release'
        required: true

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Pre-Release ${{ github.event.inputs.version }}
          body: This is a pre-release for version ${{ github.event.inputs.version }}
          draft: false
          prerelease: true
