name: Pre-Release Testing

on:
  workflow_run:
    workflows: ["Create Pre-Release"]
    types:
      - completed
    branches:
      - main

jobs:
  test-prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Say OK
        run: |
          echo "OK"
