name: Pre-Release Testing

on:
  release:
    types: [ published ]
#  workflow_run:
#    workflows: ["Create Pre-Release"]
#    types:
#      - completed
#    branches:
#      - main

jobs:
  test-prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Submit workflow start
        id: create_check
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Pre-Release Testing',
              head_sha: '${{ github.sha }}',
              status: 'in_progress',
            });
            return response.data.id;

      - name: Say OK
        run: |
          echo "OK!"

      - name: Submit result
        id: create_check_result
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Pre-Release Testing',
              head_sha: '${{ github.sha }}',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Test Results',
                summary: 'All tests passed successfully.'
              }
            });
            return response.data.id;
