name: Run tests
on:
#   push:
#     branches-ignore:
#       - main
  issue_comment:
    types:
      - created
jobs:
  tests:
    name: Run tests
    #if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Say OK
        run: |
          echo "NOT OK"
          exit 1
