name: Run unit tests
on:
  push:
#     branches-ignore:
#       - main

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Say OK
        run: |
          echo "OK"
